name: Update FX Rates Daily

on:
  schedule:
    - cron: '15 2 * * *'  # Every day at 02:15 UTC
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  update-fx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      - name: Update FX (recent 7 days)
        run: |
          python -m global_universe.fx_rates --recent 7 --buffer-days 3

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          if [ -n "$(git status --porcelain)" ]; then
            git add global_universe/data/fx/*.csv
            git commit -m "chore(fx): daily FX update (recent 7 days)"
            git push
          else
            echo "No FX updates to commit."
          fi

