name: Update Market Data

on:
  schedule:
    - cron: '20 2 * * *'  # every day at 02:20 UTC
  workflow_dispatch: {}
  push:
    branches: [ main ]
    paths:
      - 'global_universe/world_indices.py'
      - '.github/workflows/update-data.yml'

permissions:
  contents: write

concurrency:
  group: data-update
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yfinance==0.2.40 pandas==2.2.2 numpy==1.26.4

      - name: Run data updater (prices + valuations)
        env:
          MAX_SYMBOLS: ''
        run: |
          python -u global_universe/world_indices.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add -A
          if git diff --cached --quiet; then
            echo "No changes to commit"
          else
            git commit -m "data: update prices and valuations (UTC $(date -u +'%Y-%m-%d %H:%M'))"
            git push
          fi
